---
title: "Quiz 1"
author: "Francisco Martín"
date: "October 18, 2018"
output: html_document
---


### 1.- Which of the following are components in building a machine learning algorithm?

- Statistical inference
- Artificial intelligence
- Deciding on an algorithm.     (Correct)
- Training and test sets
- Machine learning

Explication -> Theory

### 2.- Suppose we build a prediction algorithm on a data set and it is 100% accurate on that data set. Why might the algorithm not work well if we collect a new data set?

- We may be using bad variables that don't explain the outcome.v
- Our algorithm may be overfitting the training data, predicting both the signal and the noise.     (Correct)
- We have too few predictors to get good out of sample accuracy.
- We have used neural networks which has notoriously bad performance.

Explication -> Theory

### 3.- What are typical sizes for the training and test sets?

- 50% training set, 50% test set
- 60% in the training set, 40% in the testing set.     (Correct)
- 90% training set, 10% test set
- 10% test set, 90% training set

Explication -> Theory

### 4.- What are some common error rates for predicting binary variables (i.e. variables with two possible values like yes/no, disease/normal, clicked/didn't click)? Check the correct answer(s).

- Predictive value of a positive       (Correct)
- Root mean squared error
- Correlation
- R^2
- Median absolute deviation

Explication -> Theory

### 5.- Suppose that we have created a machine learning algorithm that predicts whether a link will be clicked with 99% sensitivity and 99% specificity. The rate the link is clicked is 1/1000 of visits to a website. If we predict the link will be clicked on a specific visit, what is the probability it will actually be clicked?

- 99%
- 0.009%
- 9%      (Correct)
- 89.9%

Explication:

```{r explication_5}
#Supose 100 clicks 
nclicks <- 100
nvisits <- 100*1000
sensitivity <- 0.99
specificity <- 0.99
#This leads to
truepositive <- nclicks*sensitivity
falsenegative <- nclicks-truepositive
truenegative <- (nvisits-nclicks)*specificity
falsepositive <- (nvisits-nclicks)-truenegative

#Probability of actually clicked is Tp/(Tp+Fp)
prob_clicked <- truepositive/(truepositive+falsepositive)
```

So, probability of actually clicked is `r round(prob_clicked*100,2)`%
